name: dembuild 
channels:
  - defaults
  - conda-forge
dependencies:
  - conda=4.6.3
  - python=3.7
  - numpy=1.16.3
  - matplotlib=3.0.3
  - gdal=2.3.3
  - pandas=0.24.2
  - geopandas=0.4.1
  - pytz=2019.1
  - scikit-image=0.15.0
  - geos=3.7.1
  - scikit-learn=0.20.3
  - shapely=1.6.4
  - scipy=1.2.1
  - spyder=3.3.4
  - notebook=5.7.8
  - pyproj=1.9.6
  - xarray=0.12.1
  - bumpversion=0.5.3
  - wheel=0.32.1
  - flake8=3.5.0
  - tox=3.5.2
  - coverage=4.5.1
  - Sphinx=1.8.1
  - twine=1.12.1
  - pip=18.1





